project:
  type: website
  preview:
    browser: true

website:
  # Name of site in navbar
  title: "Reproducing Shoaib and Ramamohan 2022"
  # Favicon image for site
  favicon: "quarto_site/stars_logo_blue.png"
  # Adds edit and issue buttons to footer
  repo-url: https://github.com/pythonhealthdatascience/stars-reproduce-shoaib-2022
  repo-actions: [edit, issue]
  # Settings for navbar across top of page
  navbar:
    logo: "quarto_site/stars_logo_blue.png"
    # Left-aligned within navbar...
    left:
      - text: Original study
        href: quarto_site/study_publication.qmd
      - text: Reproduction
        menu:
          - text: README
            href: quarto_site/reproduction_readme.qmd
          - reproduction/reproduce_tab6.ipynb
          - reproduction/reproduce_fig2.ipynb
          - reproduction/reproduce_fig3_txt1.ipynb
          - reproduction/reproduce_fig4.ipynb
          - reproduction/reproduce_txt2.ipynb
          - reproduction/reproduce_txt34.ipynb
          - reproduction/reproduce_txt5.ipynb
      - text: Evaluation
        menu:
          - evaluation/scope.qmd
          - evaluation/reproduction_success.qmd
          - evaluation/badges.qmd
          - evaluation/artefacts.qmd
          - evaluation/reporting.qmd
      - logbook/logbook.qmd
      - text: Summary
        href: evaluation/reproduction_report.qmd
    # Right-aligned within navbar...
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/stars-reproduce-shoaib-2022
  page-footer:
    left: |
      [![](https://raw.githubusercontent.com/pythonhealthdatascience/stars-logo/main/stars_logo_blue_text.png){fig-alt="STARS" width=300px}](https://github.com/pythonhealthdatascience)
    center:
      - text: "Changelog"
        href: CHANGELOG.md
      - text: "License"
        href: quarto_site/license.qmd
      - text: "Contributing"
        href: CONTRIBUTING.md
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/stars-reproduce-shoaib-2022

format:
  html:
    theme: cosmo
    toc: true