name: shoaib2022
channels:
  - defaults
dependencies:
  - ipykernel=6.28.0
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pathlib=1.0.1
  - pip=24.0
  - python=3.9.19
  - xlsxwriter=3.1.1
  - xlwt=1.3.0
  - pip:
    - greenlet==3.0.3
    - salabim==24.0.6