name: shoaib2022
channels:
  - defaults
dependencies:
  - matplotlib=2.2.3
  - numpy=1.16.6
  - pip=19.3.1
  - python=2.7
  - statistics=1.0.3.5
  - xlsxwriter=1.3.7
  - xlwt=1.3.0
  - pip:
    - salabim==20.0.4