name: shoaib2022
channels:
  - defaults
dependencies:
  - ipykernel
  - matplotlib=3.3.4
  - nbconvert
  - notebook
  - numpy=1.20.1
  - openpyxl=3.1.2
  - pandas=1.4.4
  - pathlib=1.0.1
  - pip=21.0.1
  - python=3.9.19
  - xlrd=2.0.1
  - xlsxwriter=1.3.7
  - xlwt=1.3.0
  - pip:
    - greenlet==1.0.0
    - salabim==21.0.2